services:
  # The Unified OneClick Service
  - type: web
    name: oneclick
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
